version: '3'
services:
  db:
    image: postgres:9.6
    restart: always         
  web:
    build: .
    command: bundle exec rails s -p 3000 -b 0.0.0.0
    environment:
      RAILS_ENV: production
    volumes:
      - .:/AppWeb
    ports:
      - 127.0.0.1:33000:3000
    restart: always
    depends_on:
      - db
